### ISSUE TITLE
background gif

### ISSUE THREAD

**Issue by hamhocks** [BankkRoll/NFTGEN-nft-generator#1]
Hi, thanks for the repository. Where would I place a background gif so it doesn't hide the primary gif?

**Comment by BankkRoll** [comment]
@hamhocks Thanks!
The order you list them in here is from back to front

In the [config.js](https://github.com/BankkRoll/NFTGEN-nft-generator/blob/main/config.js) toy can edit the `traitFolders`, below is an example if we wanted a background we would do like so

`traitFolders: ["Background", "Head", "Eyes", "Mouth"], // an array of subfolder names`

**Comment by BankkRoll** [comment]
Hello, @hamhocks

I've just rolled out some important updates to the code that I think you'll appreciate. The latest version includes key bug fixes, performance optimizations, and adjustments to the intensity of the processing, all designed to make the experience smoother and more flexible for you.

I strongly encourage you to use this new version as it's been improved considerably based on the feedback received.

Thank you for your patience and understanding. Your feedback is crucial in my development journey.
