### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamhocks** [BankkRoll/NFTGEN-nft-generator#2]
Hi, thanks for the response. After npm start I get error
C:\Program Files\NFTGEN-nft-generator-main\generate.js:5
const inquirer = require('inquirer');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Program Files\NFTGEN-nft-generator-main\node_modules\inquirer\lib\inquirer.js from C:\Program Files\NFTGEN-nft-generator-main\generate.js not supported.
Instead change the require of inquirer.js in C:\Program Files\NFTGEN-nft-generator-main\generate.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Program Files\NFTGEN-nft-generator-main\generate.js:5:18) {
  code: 'ERR_REQUIRE_ESM'
}

Am I missing a module?

**Comment by BankkRoll** [comment]
Please make sure to run install first, and make sure you have node installed as well on the device.

**Comment by hamhocks** [comment]
PS C:\Program Files\NFTGEN-nft-generator-main> npm install

up to date, audited 205 packages in 659ms

found 0 vulnerabilities
PS C:\Program Files\NFTGEN-nft-generator-main> npm start

> nftgen@4.2.0 start
> node generate.js

C:\Program Files\NFTGEN-nft-generator-main\generate.js:5
const inquirer = require('inquirer');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Program Files\NFTGEN-nft-generator-main\node_modules\inquirer\lib\inquirer.js from C:\Program Files\NFTGEN-nft-generator-main\generate.js not supported.
Instead change the require of inquirer.js in C:\Program Files\NFTGEN-nft-generator-main\generate.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Program Files\NFTGEN-nft-generator-main\generate.js:5:18) {
  code: 'ERR_REQUIRE_ESM'
}
PS C:\Program Files\NFTGEN-nft-generator-main> node --version
v16.13.2

**Comment by BankkRoll** [comment]
> 
Could you please delete the whole thing and try again? I have made some changes to dynamically import inquire for this case... it seems your node version is interfearing with the inquire version...

you can try just `npm install inquirer@7.3.0` first if youd like, if not please clone the new version i have made updates to

**Comment by hamhocks** [comment]
hi should I be using a different version of node js, I'm having the same problem using the latest version with the same error .
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Program Files\NFTGEN-nft-generator-main\node_modules\ora\index.js from C:\Program Files\NFTGEN-nft-generator-main\generate.js not supported.       
Instead change the require of index.js in C:\Program Files\NFTGEN-nft-generator-main\generate.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Program Files\NFTGEN-nft-generator-main\generate.js:13:13) {
  code: 'ERR_REQUIRE_ESM'

**Comment by BankkRoll** [comment]
> hi should I be using a different version of node js, I'm having the same problem using the latest version with the same error . Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Program Files\NFTGEN-nft-generator-main\node_modules\ora\index.js from C:\Program Files\NFTGEN-nft-generator-main\generate.js not supported. Instead change the require of index.js in C:\Program Files\NFTGEN-nft-generator-main\generate.js to a dynamic import() which is available in all CommonJS modules. at Object. (C:\Program Files\NFTGEN-nft-generator-main\generate.js:13:13) { code: 'ERR_REQUIRE_ESM'



Sorry for the long reply this was a extra project i dropped on the side. it has been fixed and fully swapped to ESM so you should now not run into any errors if you download the new repo!
