### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by junyismad** [BankkRoll/NFTGEN-nft-generator#3]
i made sure i had the correct node, v. 14.21.3, and the npm is updated. i also installed inquirer per the previous issue and this is the error code i'm receiving. is there anything i'm doing wrong? i replaced the folder names in config.js with the corresponding layer folders i have

internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module './workers/animateLogs'
Require stack:
- /Users/kristina/Desktop/NFTGEN-nft-generator-main/generate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/kristina/Desktop/NFTGEN-nft-generator-main/generate.js:14:27)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/kristina/Desktop/NFTGEN-nft-generator-main/generate.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nftgen@4.2.0 start: `node generate.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nftgen@4.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BankkRoll** [comment]
> i made sure i had the correct node, v. 14.21.3, and the npm is updated. i also installed inquirer per the previous issue and this is the error code i'm receiving. is there anything i'm doing wrong? i replaced the folder names in config.js with the corresponding layer folders i have
> 
> internal/modules/cjs/loader.js:934 throw err; ^
> 
> Error: Cannot find module './workers/animateLogs' Require stack:
> 
> * /Users/kristina/Desktop/NFTGEN-nft-generator-main/generate.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:774:27)
>   at Module.require (internal/modules/cjs/loader.js:1003:19)
>   at require (internal/modules/cjs/helpers.js:107:18)
>   at Object. (/Users/kristina/Desktop/NFTGEN-nft-generator-main/generate.js:14:27)
>   at Module._compile (internal/modules/cjs/loader.js:1114:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>   at Module.load (internal/modules/cjs/loader.js:979:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:819:12)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/kristina/Desktop/NFTGEN-nft-generator-main/generate.js' ]
>   }
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! nftgen@4.2.0 start: `node generate.js`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the nftgen@4.2.0 start script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



Sorry for the long reply this was a extra project i dropped on the side. it has been fixed and fully swapped to ESM so you should now not run into any errors if you download the new repo!

**Comment by BankkRoll** [comment]
Hello, @junyismad 

I've just rolled out some important updates to the code that I think you'll appreciate. The latest version includes key bug fixes, performance optimizations, and adjustments to the intensity of the processing, all designed to make the experience smoother and more flexible for you.

I strongly encourage you to use this new version as it's been improved considerably based on the feedback received.

Thank you for your patience and understanding. Your feedback is crucial in my development journey.
