### ISSUE TITLE
cant find ora

### ISSUE THREAD

**Issue by amukreksa** [BankkRoll/NFTGEN-nft-generator#6]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ora' imported from F:\NFTGEN-nft-generator-main\NFTGEN-nft-generator-main\generate.mjs

**Comment by amukreksa** [comment]
hehehehe sorry I just had to install it

**Comment by BankkRoll** [comment]
Hey @amukreksa , no problem glad you got it solved! feel free to open another if you need any help!
