### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ora' imported from C:\Users\Mazhar\Desktop\NFT's\NFTGEN-nft-generator-main\NFTGEN-nft-generator-main\generate.mjs

### ISSUE THREAD

**Issue by mazhar0602** [BankkRoll/NFTGEN-nft-generator#7]
Please Help Me With This

**Comment by BankkRoll** [comment]
@mazhar0602 Sorry for the late response, please type `npm i ora` or `npm i ora -g` you need to install packages.. Follow the guide and they should all be installed. Thanks reopen if you still have trouble
