### ISSUE TITLE
issue with certain gif collections

### ISSUE THREAD

**Issue by meesdontmiss** [BankkRoll/NFTGEN-nft-generator#8]
Getting this error message when trying to generate one of my gif collections. has only been happening with this one but it says this error message for all the assets even thought theyre in the folder. any idea whats causing it?

"Unable to find pages property in metadata for file at path"

**Comment by BankkRoll** [comment]
@meesdontmiss  No i am not 100% sure. Have you installed install ad the config set correctly?

**Comment by BankkRoll** [comment]
Please reopen if you still need assistance!
